kind: helm-release
apiVersion: 1.0
build:
  context: .
  dockerfile: Dockerfile
install:
  chart: charts/multiple-modules-sample
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]multiple-modules-sample.<guid>.<region>.aksapp.io
      - $(spacePrefix)multiple-modules-sample$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
    container:
      imports:
      - azuredevjava/javadebug:0.1.0@/javadebug:/javadebug
      sync:
      - "**/**"
      iterate:
        processesToKill: [java]
        buildCommands:
        - [mvn, package]